with customer_order as (
SELECT
    C.CUSTOMERID,
    COALESCE(COUNT(DISTINCT O.ORDERID),0) AS NB_ORDER
FROM DBT.DBT_016_2.CUSTOMERS C
LEFT JOIN DBT.DBT_016_2.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERID
)

SELECT * FROM customer_order